mp:
  cores: 7
  epochs: 1000
  stat_file: stat.pickle
  model_list: [siam_mlp]  # possible: siam_mlp
common:
  use_obs: True
  shuffle: False
  round_episodes: 20
  players: 3
  experiment_dir: experiments
  experiment_name: main
  logging: local  # possible: no, local, local_randomly, show
train:
  do_backward: True  # use False to make agents non-trainable
  episodes: 3000
  lr: 0.001
  gamma: 1.
  hidden_size: 32
  value_loss_penalize: 0.5
  entropy_penalize: 0.05
  epsilon_upper: 0.5
  epsilon_lower: 0.001
test:
  episodes: 100
negotiation:
  use: True
  is_channel_open: True
  space: 3
  players: 2
  steps: [2]  # len(steps) must be equal to 1 or the number of players
embeddings:
  use: False
  space: 64