mp:
  cores: 4
  games: 1000
  stat_file: stat.pickle
common:
  use_obs: False
  shuffle: False
  round_episodes: 20
  players: 3
  experiment_dir: experiments
  experiment_name: transformer
  logging: local  # possible: no, local, local_randomly, show
train:
  do_backward: True  # use False to make agents non-trainable
  episodes: 30000
  lr: 0.05
  gamma: 1.
  hidden_size: 32
  value_loss_penalize: 0.5
  entropy_penalize: 0.05
  epsilon_upper: 0.5
  epsilon_lower: 0.01
test:
  episodes: 500
negotiation:
  use: True
  is_channel_open: True
  space: 2
  players: 2
  steps: [2]  # len(steps) must be equal to 1 or the number of players
embeddings:
  use: False
  space: 64